# Generated by Django 4.2.1 on 2023-05-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('music_name', models.CharField(max_length=50)),
                ('music_url', models.CharField(max_length=50)),
                ('frame_nbr', models.IntegerField()),
                ('time', models.FloatField()),
                ('video_url', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reels.category')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=0)),
                ('time', models.FloatField()),
                ('fixe', models.BooleanField(default=0)),
                ('url', models.CharField(max_length=50)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reels.animation')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reels.template')),
            ],
        ),
    ]
