# Generated by Django 4.2.1 on 2023-05-17 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0004_block_delete_video_remove_frame_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='reels.animation'),
        ),
    ]
