# Generated by Django 4.2.1 on 2023-05-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0005_block_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='reels.animation'),
        ),
        migrations.AddField(
            model_name='frame',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='reels.template'),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
