# Generated by Django 4.2.1 on 2023-05-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0006_frame_animation_frame_template_delete_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='type',
        ),
        migrations.AddField(
            model_name='frame',
            name='isImage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='animation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='reels.animation'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='url',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
