# Generated by Django 4.2.1 on 2023-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0007_remove_frame_type_frame_isimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='video',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
