# Generated by Django 4.2.1 on 2023-05-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0010_alter_frame_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='video',
            field=models.FileField(upload_to='animations/'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='url',
            field=models.FileField(default='', upload_to='frames/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='video_url',
            field=models.FileField(upload_to='templates/'),
        ),
    ]
