# Generated by Django 4.2.1 on 2023-05-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0013_alter_template_music_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='music_url',
            field=models.FileField(max_length=255, upload_to='music/'),
        ),
    ]
