# Generated by Django 4.2.1 on 2023-06-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0016_alter_like_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='reels.template'),
        ),
    ]
