# Generated by Django 4.2.1 on 2023-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0018_alter_like_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='url',
            field=models.FileField(default=None, upload_to='frames/'),
        ),
    ]
