# Generated by Django 4.2.1 on 2023-06-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0020_alter_frame_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='video',
            field=models.FileField(blank=True, upload_to='animations/'),
        ),
    ]
